"""Seed all CMS content parsed from the original static site.

Reads scripts/seed_data.json (generated by scripts/build_base_home.py +
scripts/build_arcade.py) plus the built-in event catalogue.
Idempotent — safe to re-run (uses update_or_create on natural keys).

Run: uv run python manage.py seed_site
"""

import json
from pathlib import Path

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils.text import slugify

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent


class Command(BaseCommand):
    help = "Seed CMS content, events and games from the legacy static site."

    def handle(self, *args, **options):
        seed_path = BASE_DIR / "scripts" / "seed_data.json"
        seed = json.loads(seed_path.read_text(encoding="utf-8"))

        from blog.models import Post
        from django.conf import settings as dj_settings
        from django.contrib.sites.models import Site
        from core.models import (
            CommitteeCategory,
            CommitteeMember,
            Competition,
            CompetitionDetail,
            CompetitionTag,
            FAQ,
            Game,
            Guest,
            HeroChip,
            SiteSetting,
            Sponsor,
            Stat,
            TickerItem,
            TimelineStep,
        )
        from registrations.models import Event, Registration

        with transaction.atomic():
            SiteSetting.get_solo()
            self.stdout.write("site settings: ok")

            # Keep django.contrib.sites in sync so sitemaps/emails use the real domain.
            try:
                from urllib.parse import urlparse

                host = urlparse(getattr(dj_settings, "SITE_URL", "")).hostname or "bbccictfest.pro.bd"
                Site.objects.update_or_create(
                    id=getattr(dj_settings, "SITE_ID", 1),
                    defaults={"domain": host, "name": "BBCC ICT Fest 2026"},
                )
            except Exception as exc:  # pragma: no cover - non-fatal
                self.stdout.write(f"site domain sync skipped: {exc}")

            for i, chip in enumerate(seed.get("chips", [])):
                HeroChip.objects.update_or_create(
                    order=i, defaults={"html": chip["html"], "css_class": chip["css_class"], "is_active": True}
                )
            for i, text in enumerate(seed.get("ticker", [])):
                TickerItem.objects.update_or_create(
                    order=i, defaults={"html": text, "is_active": True}
                )
            for i, stat in enumerate(seed.get("stats", [])):
                Stat.objects.update_or_create(
                    order=i,
                    defaults={"value": stat["value"], "suffix": stat["suffix"], "label": stat["label"]},
                )
            self.stdout.write(
                f"chips={len(seed.get('chips', []))} ticker={len(seed.get('ticker', []))} stats={len(seed.get('stats', []))}"
            )

            for i, comp in enumerate(seed.get("competitions", [])):
                obj, _ = Competition.objects.update_or_create(
                    slug=comp["slug"],
                    defaults={
                        "title": comp["title"][:160],
                        "icon_svg": comp.get("icon_svg", ""),
                        "icon_class": comp.get("icon_class", "comp-icon-1"),
                        "description": comp.get("description", ""),
                        "order": i,
                        "is_active": True,
                    },
                )
                obj.tags.all().delete()
                for j, (text, highlight) in enumerate(comp.get("tags", [])):
                    CompetitionTag.objects.create(
                        competition=obj, text=text[:80], highlight=highlight, order=j
                    )
                obj.details.all().delete()
                for j, text in enumerate(comp.get("details", [])):
                    CompetitionDetail.objects.create(
                        competition=obj, text=text[:255], order=j
                    )
            self.stdout.write(f"competitions={len(seed.get('competitions', []))}")

            for i, step in enumerate(seed.get("timeline", [])):
                TimelineStep.objects.update_or_create(
                    order=i,
                    defaults={
                        "step_no": int(step.get("no") or i + 1),
                        "tag": step.get("tag", "")[:60],
                        "title": step.get("title", "")[:160],
                        "text": step.get("text", ""),
                        "dot_class": step.get("dot", "tl-dot-1"),
                    },
                )

            for i, guest in enumerate(seed.get("guests", [])):
                Guest.objects.update_or_create(
                    role=guest.get("role", "")[:120],
                    defaults={
                        "name": guest.get("name", "")[:160],
                        "bio": guest.get("bio", ""),
                        "image_url": guest.get("image_url", "")[:500],
                        "avatar_class": guest.get("avatar_class", "g-a1"),
                        "is_featured": bool(guest.get("featured")),
                        "order": i,
                        "is_active": True,
                    },
                )

            for i, cat in enumerate(seed.get("committee", [])):
                cat_obj, _ = CommitteeCategory.objects.update_or_create(
                    slug=cat.get("slug") or slugify(cat["name"])[:50],
                    defaults={"name": cat["name"][:160], "order": i},
                )
                for j, member in enumerate(cat.get("members", [])):
                    CommitteeMember.objects.update_or_create(
                        category=cat_obj,
                        name=member["name"][:160],
                        defaults={
                            "role": member.get("role", "")[:160],
                            "image_url": member.get("image_url", "")[:500],
                            "order": j,
                            "is_active": True,
                        },
                    )
            self.stdout.write(f"committee cats={len(seed.get('committee', []))}")

            for i, spon in enumerate(seed.get("sponsors", [])):
                Sponsor.objects.update_or_create(
                    name=spon["name"][:160],
                    defaults={"is_surprise": bool(spon.get("surprise")), "order": i, "is_active": True},
                )

            for i, faq in enumerate(seed.get("faqs", [])):
                FAQ.objects.update_or_create(
                    question=faq["q"][:255],
                    defaults={"answer": faq["a"], "order": i, "is_active": True},
                )
            self.stdout.write(f"faqs={len(seed.get('faqs', []))}")

            for i, game in enumerate(seed.get("games", [])):
                Game.objects.update_or_create(
                    slug=game["slug"],
                    defaults={
                        "title": game["title"][:120],
                        "description": game.get("description", ""),
                        "difficulty": game.get("difficulty", "Arcade")[:40],
                        "icon_svg": game.get("icon_svg", ""),
                        "icon_class": game.get("icon_class", "g-1")[:10],
                        "accent_color": game.get("accent_color", "#FF7A1A")[:20],
                        "order": i,
                        "is_active": True,
                    },
                )
            self.stdout.write(f"games={len(seed.get('games', []))}")

            events = [
                {
                    "name": "ICT Quiz", "slug": "ict-quiz", "kind": "quiz", "fee_bdt": 19,
                    "is_team_event": False, "order": 0,
                    "short_description": "Test your knowledge of ICT, computers and digital innovation. Open to all — on-the-spot participation available.",
                },
                {
                    "name": "Science Project Showdown", "slug": "science-showdown", "kind": "science", "fee_bdt": 0,
                    "is_team_event": True, "order": 1,
                    "short_description": "Represent your school with a team of 2 students + 1 teacher. Dedicated stall, top 10 teams on the main stage.",
                },
                {
                    "name": "Coding Competition", "slug": "coding", "kind": "coding", "fee_bdt": 49,
                    "is_team_event": False, "order": 2,
                    "short_description": "Solo timed challenge on real-world programming problems. Online selection, top 5 battle on the main stage.",
                },
                {
                    "name": "Chess", "slug": "chess", "kind": "chess", "fee_bdt": 0,
                    "is_team_event": False, "order": 3,
                    "short_description": "Knockout battles on the 64-square board. Free registration, open to all.",
                },
                {
                    "name": "Rubik's Cube", "slug": "rubiks-cube", "kind": "rubiks", "fee_bdt": 0,
                    "is_team_event": False, "order": 4,
                    "short_description": "Head-to-head timed 3x3 solves. Bring your own cube — top 5 face the live final before the judges.",
                },
            ]
            for ev in events:
                Event.objects.update_or_create(slug=ev["slug"], defaults={**ev, "is_active": True})
            self.stdout.write(f"events={len(events)}")

            # Schools from every distinct institution already on file.
            from schools.models import School

            institutions = {
                name.strip()
                for name in Registration.objects.values_list("institution", flat=True)
                if name and name.strip()
            }
            for i, name in enumerate(sorted(institutions)):
                School.objects.get_or_create(
                    name=name[:200], defaults={"order": i}
                )
            self.stdout.write(f"schools={School.objects.count()}")

            User = get_user_model()
            author = User.objects.filter(is_staff=True).first() or User.objects.first()
            if author is not None and not Post.objects.filter(slug="welcome-to-bbcc-ict-fest-2026").exists():
                Post.objects.create(
                    title="Welcome to BBCC ICT Fest 2026",
                    slug="welcome-to-bbcc-ict-fest-2026",
                    excerpt="Registrations are open — quiz, science showdown, coding, chess and Rubik's cube.",
                    content=(
                        "Bindubasini Boys' Computer Club proudly presents the biggest ICT festival "
                        "in the history of Tangail district.\n\nFive competitions, distinguished guests, "
                        "school exhibitions and a full day of innovation await you on September 19, 2026 "
                        "at Bindubasini Boys' School.\n\nRegister for your event, pay securely with bKash, "
                        "and take a break at the BBCC Arcade between competitions. See you there!"
                    ),
                    author=author,
                    status=Post.STATUS_PUBLISHED,
                )
                self.stdout.write("welcome post: created")
            else:
                self.stdout.write("welcome post: skipped (no users yet or exists)")

        self.style.SUCCESS("Seeding complete.")
