# Generated by Django 6.1.1 on 2026-09-10 02:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Adviser Panel (Teachers)', max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Committee categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('icon_svg', models.TextField(blank=True, help_text="Inline SVG (inner content of the icon). Keep stroke='currentColor'.")),
                ('icon_class', models.CharField(default='comp-icon-1', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Matches the legacy file name, e.g. snake', unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='Easy', max_length=40)),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG for the arcade card icon (inner <svg>…</svg>).')),
                ('icon_class', models.CharField(default='g-1', help_text='g-1 … g-25', max_length=10)),
                ('accent_color', models.CharField(default='#FF7A1A', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(help_text='e.g. Chief Guest', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Photo URL')),
                ('avatar_class', models.CharField(default='g-a1', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(help_text='Inline HTML allowed, e.g. $ <b>fest</b> --kickoff', max_length=255)),
                ('css_class', models.CharField(default='chip-1', help_text='chip-1 … chip-4', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BBCC ICT Fest 2026', max_length=120)),
                ('org_name', models.CharField(default="Bindubasini Boys' Computer Club", max_length=160)),
                ('tagline', models.CharField(default='Biggest ICT Festival in Tangail', max_length=200)),
                ('hero_kicker', models.CharField(default='Registrations are Open', max_length=120)),
                ('hero_title_line1', models.CharField(default='ICT FEST', max_length=120)),
                ('hero_title_line2', models.CharField(default='2026', max_length=120)),
                ('hero_subtitle', models.TextField(default="Tangail's biggest technology festival — five competitions, extraordinary guests, and a full day of innovation.")),
                ('event_date', models.DateTimeField(default=datetime.datetime(2026, 9, 18, 9, 0))),
                ('venue_name', models.CharField(default="Bindubasini Boys' School, Tangail", max_length=160)),
                ('venue_address', models.CharField(default="Bindubasini Boys' School, Tangail, Bangladesh", max_length=255)),
                ('participants_label', models.CharField(default='1000+ Participants', max_length=60)),
                ('contact_email', models.EmailField(default='club.bbcc@gmail.com', max_length=254)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/bbcompuerclub', max_length=500)),
                ('footer_about', models.TextField(default="The Biggest ICT Festival in Tangail District. Organized by Bindubasini Boys' Computer Club bringing technology and innovation to the forefront of education.")),
                ('made_by_name', models.CharField(default='Md Abu Salehin', max_length=120)),
                ('made_by_url', models.URLField(default='https://mdsalehin.netlify.app/', max_length=500)),
                ('meta_description', models.TextField(default="Tangail's biggest ICT festival — ICT Quiz, Science Project Showdown, Coding Competition, Chess & Rubik's Cube. September 18, 2026 at Bindubasini Boys' School. Register now!")),
                ('og_image_url', models.URLField(default='https://bbccictfest.pro.bd/logo.png', max_length=500, verbose_name='Social share image URL')),
                ('registration_open', models.BooleanField(default=True)),
                ('ca_open', models.BooleanField(default=True, verbose_name='Campus Ambassador applications open')),
                ('about_heading_a', models.CharField(default='The Biggest ICT Event', max_length=200)),
                ('about_heading_b', models.CharField(default='In the History of Tangail District', max_length=200)),
                ('about_para1', models.TextField(default="Bindubasini Boys' Computer Club presents the inaugural ICT Fest — a landmark event uniting students, educators, and innovators from across Tangail for a celebration of technology and creativity.")),
                ('about_para2', models.TextField(default="With five distinct competitions — ICT Quiz, Science Project Showdown, Coding Competition, Chess, Rubik's Cube — plus distinguished guests and school exhibitions, this is the largest technology festival the district has ever witnessed.")),
                ('cta_tag', models.CharField(default='Are You', max_length=60)),
                ('cta_title_a', models.CharField(default='Ready to Be Part of', max_length=200)),
                ('cta_title_b', models.CharField(default='The Biggest ICT Fest?', max_length=200)),
                ('cta_subtitle', models.TextField(default="Registrations are open. Secure your spot at Tangail's biggest technology celebration!")),
                ('ca_heading', models.CharField(default='Become a Campus Ambassador', max_length=200)),
                ('ca_description', models.TextField(default='Represent BBCC ICT Fest 2026 at your school or college. Lead promotions, build your network, and earn exclusive perks — certificate, crest, and priority access on fest day.')),
                ('committee_note', models.CharField(default='Photos coming soon', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('is_surprise', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, help_text='Animated counter target')),
                ('suffix', models.CharField(blank=True, default='', help_text='e.g. +', max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(help_text='Inline HTML allowed, e.g. ICT QUIZ or <b>1000+</b> PARTICIPANTS', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(default=1)),
                ('tag', models.CharField(help_text='e.g. Step 01 Register', max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('dot_class', models.CharField(default='tl-dot-1', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(max_length=160)),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Photo URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.committeecategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.competition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.competition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('comment', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
