# Generated by Django 6.1.1 on 2026-09-10 02:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='event_date',
            field=models.DateTimeField(default=core.models.default_event_date),
        ),
    ]
