# Generated by Django 6.1.1 on 2026-09-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(default="Tangail's biggest ICT festival — ICT Quiz, Science Project Showdown, Coding Competition, Chess & Rubik's Cube. September 19, 2026 at Bindubasini Boys' School. Register now!"),
        ),
    ]
