# Generated by Django 6.1.1 on 2026-09-10 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesetting_meta_description'),
        ('registrations', '0002_campusambassadorapplication_school'),
        ('volunteers', '0002_volunteer_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('comment', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_reviews', to='registrations.campusambassadorapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_reviews', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_reviews', to='volunteers.volunteer')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'volunteer'), name='unique_user_volunteer_review'), models.UniqueConstraint(fields=('user', 'ambassador'), name='unique_user_ambassador_review'), models.CheckConstraint(condition=models.Q(models.Q(('ambassador__isnull', False), ('volunteer__isnull', True)), models.Q(('ambassador__isnull', True), ('volunteer__isnull', False)), _connector='OR'), name='person_review_single_target')],
            },
        ),
    ]
