# Generated by Django 6.1.1 on 2026-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='register_status',
            field=models.BooleanField(default=True, verbose_name='Registration open'),
        ),
    ]
