# Generated by Django 6.1.1 on 2026-09-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesetting_register_status'),
        ('volunteers', '0002_volunteer_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personreview',
            name='unique_user_ambassador_review',
        ),
        migrations.RemoveConstraint(
            model_name='personreview',
            name='person_review_single_target',
        ),
        migrations.AddField(
            model_name='personreview',
            name='ambassador_user',
            field=models.ForeignKey(blank=True, help_text='The Campus Ambassador (user) being rated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='personreview',
            constraint=models.UniqueConstraint(fields=('user', 'ambassador_user'), name='unique_user_ambassador_review'),
        ),
        migrations.AddConstraint(
            model_name='personreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ambassador_user__isnull', False), ('volunteer__isnull', True)), models.Q(('ambassador_user__isnull', True), ('volunteer__isnull', False)), _connector='OR'), name='person_review_single_target'),
        ),
        migrations.RemoveField(
            model_name='personreview',
            name='ambassador',
        ),
    ]
