# Generated by Django 6.1.1 on 2026-09-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_personreview_unique_user_ambassador_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='ca_open',
        ),
    ]
