# Generated by Django 6.1.1 on 2026-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sitesetting_ca_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='cta_subtitle',
            field=models.TextField(default='Registrations are offline only. Sign up on paper at your school or at the venue help desk!'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_kicker',
            field=models.CharField(default='Registrations Offline', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(default="Tangail's biggest ICT festival — ICT Quiz, Science Project Showdown, Coding Competition, Chess & Rubik's Cube. September 19, 2026 at Bindubasini Boys' School. Registrations offline only!"),
        ),
    ]
