# Generated by Django 6.1.1 on 2026-09-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesetting_cta_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='register_status',
        ),
    ]
