# Generated by Django 6.1.1 on 2026-09-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(default='Volunteer', help_text='e.g. Volunteer — Logistics', max_length=160)),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Photo URL')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
