# Generated by Django 6.1.1 on 2026-09-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='school',
            field=models.ForeignKey(blank=True, help_text="The volunteer's school. Each school's volunteers appear under its Campus Ambassador.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='schools.school'),
        ),
    ]
