# Generated by Django 6.1.1 on 2026-09-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user represents as Campus Ambassador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer'), ('campus_ambassador', 'Campus Ambassador'), ('organizer', 'Organizer')], default='participant', max_length=20),
        ),
    ]
