# Generated by Django 6.1.1 on 2026-09-10 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('quiz', 'ICT Quiz'), ('science', 'Science Project Showdown'), ('coding', 'Coding Competition'), ('chess', 'Chess'), ('rubiks', "Rubik's Cube")], default='quiz', max_length=20)),
                ('fee_bdt', models.PositiveIntegerField(default=0, help_text='Registration fee in BDT. 0 = free, skips bKash.')),
                ('is_team_event', models.BooleanField(default=False, help_text='Science showdown: 2 students + 1 teacher.')),
                ('short_description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=50, verbose_name='Class')),
                ('team_name', models.CharField(blank=True, max_length=160)),
                ('teammate_name', models.CharField(blank=True, max_length=160, verbose_name='Teammate name')),
                ('teacher_name', models.CharField(blank=True, max_length=160, verbose_name='Teacher name')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_bdt', models.PositiveIntegerField(default=0)),
                ('bkash_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bkash_trx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bkash_customer_msisdn', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100)),
                ('trx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount_bdt', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated (create)'), ('callback_success', 'Callback: success'), ('callback_fail', 'Callback: failed'), ('callback_cancel', 'Callback: cancelled'), ('executed', 'Executed'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('payer_reference', models.CharField(blank=True, max_length=160)),
                ('bkash_url', models.URLField(blank=True, max_length=1000)),
                ('raw_create', models.JSONField(blank=True, default=dict)),
                ('raw_execute', models.JSONField(blank=True, default=dict)),
                ('raw_query', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusAmbassadorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=50, verbose_name='Class')),
                ('district', models.CharField(default='Tangail', max_length=100)),
                ('motivation', models.TextField(help_text='Why do you want to be a Campus Ambassador?')),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_ca_application_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
    ]
