# Generated by Django 6.1.1 on 2026-09-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='school',
            field=models.ForeignKey(help_text='Required — every Campus Ambassador must belong to a school.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ambassadors', to='schools.school'),
        ),
    ]
