# Generated by Django 6.1.1 on 2026-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_campusambassadorapplication_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
