# Generated by Django 6.1.1 on 2026-09-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_registration_user'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registration',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Participant's school (drives CA dashboards and fest-day search).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='schools.school'),
        ),
        migrations.AddField(
            model_name='registration',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number from the offline paper form, if any.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='class_name',
            field=models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('Other', 'Other')], max_length=50, verbose_name='Class'),
        ),
    ]
