# Generated by Django 6.1.1 on 2026-09-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_personreview_unique_user_ambassador_review_and_more'),
        ('registrations', '0005_paymenttransaction_group_id_registration_checked_in_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campusambassadorapplication',
            name='unique_ca_application_per_user',
        ),
        migrations.DeleteModel(
            name='CampusAmbassadorApplication',
        ),
    ]
